# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0015_employee_second_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=90, verbose_name='full name'),
        ),
    ]
