# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20160518_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='Задача'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='task.Attachment', verbose_name='Файлы'),
        ),
    ]
